name: Docker Test
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show workspace
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          ls -al
          ls -al work/ch11/ex01/test_repository || true

      - name: Build image (Dockerfile in subdir)
        run: |
          docker image build \
            -f work/ch11/ex01/test_repository/Dockerfile \
            -t myflask-test \
            work/ch11/ex01/test_repository

      - name: Run container and test
        run: |
          docker container run -d --name myflask-ac -p 8001:8001 myflask-test
          sleep 10
          curl -f http://127.0.0.1:8001
      - name: Cleanup
        run: |
          docker container rm -f myflask-ac || true

